# # sersitive blue: #6C9BC0
# # ~sersitive gold: #DBBD8A
# #  gold: #eedda9
# # alternative color for background: #F5F1FB

[theme]
primaryColor='#6C9BC0'  # radiobuttons etc
backgroundColor="#FFF"  # Main color
secondaryBackgroundColor="#d3d4db"  # sidebar color
textColor="#262730"
font="sans serif"
